apiVersion: v1
kind: Namespace
metadata:
  name: ian-day2-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: sites-sub
---
apiVersion: v1
kind: Namespace
metadata:
  name: groups-sub
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ian-day2
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ian-day2-app
  project: ian-project-day2
  source:
    path: test-day2
    repoURL: https://ztp-gitea-gitea.apps.clus2.t5g.lab.eng.bos.redhat.com/imiller/scratchpad.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
