apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
    name: disconnected-internal-icsp
spec:
    repositoryDigestMirrors:
    - mirrors:
      - registry.example.com:5000
      source: registry.redhat.io
